/* =========================================================================
   The same model, written out as Python.

   This panel is the point of the whole artefact for an engineer who will
   one day sit across a table from a supplier. The blocks are not a toy
   language that happens to resemble machine learning — they are a picture
   of about forty lines of pandas and Keras, and here are the forty lines.
   Every number in the code comes from a field on a block, so changing a
   block changes the code in front of you.
   ========================================================================= */
'use strict';

const PY = {
  esc: s => String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;'),
  /* a deliberately small highlighter — comments, strings, keywords, numbers */
  hl(src){
    const KW = /\b(import|from|as|def|return|for|in|if|else|elif|None|True|False|with|print|lambda)\b/g;
    return this.esc(src)
      .replace(/(#[^\n]*)/g, '<span class="c">$1</span>')
      .replace(/('[^'\n]*'|"[^"\n]*")/g, '<span class="s">$1</span>')
      .replace(KW, '<span class="k">$1</span>')
      .replace(/\b(\d+\.?\d*)\b/g, '<span class="n">$1</span>');
  }
};

function pyName(s){
  return String(s).toLowerCase()
    .replace(/[^a-z0-9]+/g, '_').replace(/^_+|_+$/g, '').slice(0, 40) || 'tag';
}

function generatePython(spec){
  const errs = validate(spec);
  if (errs.length) return '# Finish the model first:\n' + errs.map(e => '#   - ' + e).join('\n');

  const d = MB.data;
  const ds  = spec.find(b => b.type === 'dataset');
  const csv = spec.find(b => b.type === 'csv');
  const ins = spec.find(b => b.type === 'inputs');
  const tgt = spec.find(b => b.type === 'target');
  const win = spec.find(b => b.type === 'window') || {f:{from:0, to:180}};
  const tr  = spec.find(b => b.type === 'train');
  const al  = spec.find(b => b.type === 'alert');
  const layers = spec.filter(b => b.type === 'dense');
  const norm = spec.some(b => b.type === 'normalise');
  const lags = spec.filter(b => b.type === 'lag');
  const rolls = spec.filter(b => b.type === 'roll');

  const feats = (ins.f.tags || []).filter(t => t !== tgt.f.tag);
  const fcols = feats.map(id => pyName(tagName(id)));
  const ycol  = pyName(tagName(tgt.f.tag));

  const L = [];
  L.push('# ' + (d ? d.name : 'plant machine') + ' — expected-versus-actual model');
  L.push('# Generated by the Model Builder from the blocks on your canvas.');
  L.push('# Every number below came from a field you set.');
  L.push('');
  L.push('import pandas as pd');
  L.push('import numpy as np');
  L.push('from tensorflow import keras');
  L.push('from tensorflow.keras import layers');
  L.push('');
  if (csv) {
    L.push('# 1. Your export. One row per timestamp, one column per tag.');
    L.push("df = pd.read_csv('export.csv', parse_dates=['timestamp'])");
    L.push("df = df.set_index('timestamp').sort_index()");
  } else {
    L.push('# 1. One year of hourly readings, ' + (d ? d.tags.length : 0) + ' tags.');
    L.push('#    From your historian this is a tag-by-tag export at 1 h interval.');
    L.push("df = pd.read_csv('" + (ds ? ds.f.case : 'machine') + "_year.csv', parse_dates=['timestamp'])");
    L.push("df = df.set_index('timestamp').sort_index()");
  }
  L.push('');
  L.push('FEATURES = [' + fcols.map(c => `'${c}'`).join(', ') + ']');
  L.push(`TARGET   = '${ycol}'`);
  L.push('');

  if (lags.length || rolls.length){
    L.push('# 2. Engineered inputs — exactly the Prepare blocks, in order.');
    for (const b of lags){
      const h = Math.round(b.f.h);
      L.push(`for c in list(FEATURES):`);
      L.push(`    df[f'{c}_lag${h}'] = df[c].shift(${h})        # what it was doing ${h} h ago`);
      L.push(`FEATURES += [f'{c}_lag${h}' for c in ` + JSON.stringify(fcols).replace(/"/g, "'") + ']');
    }
    for (const b of rolls){
      const h = Math.round(b.f.h);
      L.push(`for c in list(FEATURES):`);
      L.push(`    df[f'{c}_roll${h}'] = df[c].rolling(${h}, min_periods=1).mean()`);
      L.push(`FEATURES += [f'{c}_roll${h}' for c in ` + JSON.stringify(fcols).replace(/"/g, "'") + ']');
    }
    L.push('df = df.dropna()');
    L.push('');
  }

  const a = Math.round(win.f.from), b2 = Math.round(win.f.to);
  L.push('# 3. The training window. This is the single most consequential line');
  L.push('#    in the file: the model can only learn what happened inside it.');
  L.push(`train = df.iloc[${a * 24}:${b2 * 24}]        # day ${a} to day ${b2}`);
  L.push('');
  L.push('X_train, y_train = train[FEATURES].values, train[TARGET].values');
  L.push('X_all,   y_all   = df[FEATURES].values,    df[TARGET].values');
  L.push('');

  if (norm){
    L.push('# 4. Standardise on the TRAINING window only. Fitting the scaler on');
    L.push('#    the whole file leaks the future into the model and every');
    L.push('#    validation number after it becomes fiction.');
    L.push('mu, sigma = X_train.mean(0), X_train.std(0) + 1e-9');
    L.push('ym, ys    = y_train.mean(),  y_train.std() + 1e-9');
    L.push('X_train, X_all = (X_train - mu) / sigma, (X_all - mu) / sigma');
    L.push('y_train_s = (y_train - ym) / ys');
    L.push('');
  } else {
    L.push('# 4. No Normalise block, so the raw units go straight in. With tags');
    L.push('#    in °C, %, A and mm/s at once this usually trains badly.');
    L.push('ym, ys, y_train_s = 0.0, 1.0, y_train');
    L.push('');
  }

  L.push('# 5. The network — one line per Hidden layer block.');
  L.push('model = keras.Sequential([');
  L.push('    layers.Input(shape=(len(FEATURES),)),');
  for (const l of layers) L.push(`    layers.Dense(${Math.round(l.f.n)}, activation='${l.f.act}'),`);
  L.push("    layers.Dense(1),                       # the expected value");
  L.push('])');
  L.push(`model.compile(optimizer=keras.optimizers.SGD(learning_rate=${(+tr.f.lr).toFixed(3)}), loss='mse')`);
  L.push(`model.fit(X_train, y_train_s, epochs=${Math.round(tr.f.epochs)}, batch_size=1, verbose=0)`);
  L.push('');
  L.push('# 6. Expected versus actual, for every hour of the year.');
  L.push('expected = model.predict(X_all, verbose=0).ravel() * ys + ym');
  L.push("df['expected'] = expected");
  L.push("df['residual'] = y_all - expected");
  L.push('');

  if (al){
    const k = +al.f.k, h = Math.round(al.f.hours);
    L.push('# 7. The alert rule. The band comes from the residual inside the');
    L.push('#    training window — the machine when it was known to be well.');
    L.push(`resid_sigma = df['residual'].iloc[${a * 24}:${b2 * 24}].std()`);
    L.push(`over = df['residual'].abs() > ${k} * resid_sigma`);
    L.push(`sustained = over.rolling(${h}).sum() == ${h}     # ${h} hours in a row, not one spike`);
    L.push("alerts = df.index[sustained & ~sustained.shift(1, fill_value=False)]");
    L.push("print(f'{len(alerts)} advisories; first at {alerts[0] if len(alerts) else None}')");
  }
  return L.join('\n');
}
