#!/usr/bin/env python3
"""Build the participant documents in dist/ from the markdown in course/.

This script exists because the previous Word file was built by hand, once, and
then silently went stale: it was three days and one whole chapter behind the
markdown, and contained none of the figures. A deliverable with no build step
is a deliverable that is wrong and does not say so.

    python3 tools/build_docs.py            course material, docx + pdf
    python3 tools/build_docs.py --no-pdf   skip the LibreOffice pass
    python3 tools/build_docs.py --check    fail if dist/ is older than course/

Figures are authored as SVG so they render on GitHub and stay sharp in the
browser. Word cannot place SVG without a rasteriser present, so the build
swaps each reference for the PNG beside it. Both are generated by
course/figures/make_figures.py and both are committed.
"""
import argparse, os, re, shutil, subprocess, sys, tempfile, time

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
COURSE = os.path.join(ROOT, 'course')
DIST = os.path.join(ROOT, 'dist')
FIGS = os.path.join(COURSE, 'figures')

DOCS = [{
    'src': 'course_material.md',
    'out': 'AI_in_Power_Plants_MAHAGENCO_Course_Material',
    'title': 'AI in Power Plants: From Data to Decisions',
    'subtitle': 'Course material, handouts and delivery script — MAHAGENCO Training Centre, Nashik',
}]


def run(cmd, **kw):
    r = subprocess.run(cmd, capture_output=True, text=True, **kw)
    if r.returncode != 0:
        sys.exit(f'FAILED: {" ".join(cmd[:3])}…\n{r.stderr[:1500]}')
    return r


def need(tool):
    if not shutil.which(tool):
        sys.exit(f'{tool} is not installed. apt-get install {tool}')


def reference_doc(tmp):
    """Pandoc's default reference, restyled to the house look: a serif face for
       headings, ink rather than the default blue, and tighter table rules."""
    ref = os.path.join(tmp, 'reference.docx')
    with open(ref, 'wb') as f:
        f.write(subprocess.run(['pandoc', '--print-default-data-file', 'reference.docx'],
                               capture_output=True).stdout)
    un = os.path.join(tmp, 'ref')
    run(['unzip', '-q', ref, '-d', un])
    p = os.path.join(un, 'word', 'styles.xml')
    x = open(p, encoding='utf-8').read()

    # heading colour: pandoc's default is a mid blue; the pack is ink + ember
    x = x.replace('w:val="365F91"', 'w:val="1C2530"')
    x = x.replace('w:val="4F81BD"', 'w:val="1C2530"')
    # headings in the same serif the deck uses for titles
    x = re.sub(r'(<w:style [^>]*w:styleId="Heading[1-3]".*?)(<w:rPr>)',
               r'\1\2<w:rFonts w:ascii="Georgia" w:hAnsi="Georgia" w:cs="Georgia"/>',
               x, flags=re.S)
    # body text a touch larger and looser than pandoc's default
    x = x.replace('<w:sz w:val="22"/>', '<w:sz w:val="21"/>')
    open(p, 'w', encoding='utf-8').write(x)
    os.remove(ref)
    run(['zip', '-Xrq', ref, '.'], cwd=un)
    return ref


def preprocess(src_path, tmp):
    """SVG -> PNG for Word, and give the document a title block pandoc can use."""
    md = open(src_path, encoding='utf-8').read()
    missing = []
    for m in re.finditer(r'\(figures/([\w.-]+)\.svg\)', md):
        png = os.path.join(FIGS, m.group(1) + '.png')
        if not os.path.exists(png):
            missing.append(m.group(1) + '.png')
    if missing:
        sys.exit('missing raster figures: ' + ', '.join(missing) +
                 '\nrun: python3 course/figures/make_figures.py && '
                 'node tools/rasterise_figures.js')
    md = re.sub(r'\(figures/([\w.-]+)\.svg\)', r'(figures/\1.png)', md)
    out = os.path.join(tmp, 'body.md')
    open(out, 'w', encoding='utf-8').write(md)
    return out


def build(doc, ref, tmp, want_pdf):
    src = os.path.join(COURSE, doc['src'])
    body = preprocess(src, tmp)
    docx = os.path.join(DIST, doc['out'] + '.docx')
    run(['pandoc', body,
         # 48 horizontal rules in the source; without -yaml_metadata_block pandoc reads
         # the first '---' after a blank line as the start of a metadata block.
         # -implicit_figures: otherwise pandoc turns the alt text into a caption AND
         # the italic line under each figure stays, so every figure gets two.
         # Dropping it keeps alt text in the XML for screen readers.
         '-f', 'markdown-yaml_metadata_block-implicit_figures+pipe_tables+grid_tables',
         '-t', 'docx', '-o', docx,
         '--reference-doc', ref,
         '--toc', '--toc-depth=3',
         '--resource-path', COURSE,
         '-M', f'title={doc["title"]}',
         '-M', f'subtitle={doc["subtitle"]}',
         '-V', 'lang=en-GB'],
        cwd=COURSE)
    print(f'  {os.path.basename(docx):58s} {os.path.getsize(docx)/1048576:5.2f} MB')

    if not want_pdf:
        return docx, None
    need('soffice')
    outdir = os.path.join(tmp, 'pdf')
    run(['soffice', '--headless', '--convert-to', 'pdf', '--outdir', outdir, docx],
        cwd=tmp)
    made = os.path.join(outdir, doc['out'] + '.pdf')
    pdf = os.path.join(DIST, doc['out'] + '.pdf')
    shutil.move(made, pdf)
    pages = len(re.findall(rb'/Type\s*/Page[^s]', open(pdf, 'rb').read()))
    print(f'  {os.path.basename(pdf):58s} {os.path.getsize(pdf)/1048576:5.2f} MB   {pages} pages')
    return docx, pdf


def check():
    """Is anything in dist/ older than the markdown it is built from?"""
    stale = []
    for doc in DOCS:
        src = os.path.getmtime(os.path.join(COURSE, doc['src']))
        newest_fig = max([os.path.getmtime(os.path.join(FIGS, f))
                          for f in os.listdir(FIGS) if f.endswith('.png')] or [0])
        for ext in ('.docx', '.pdf'):
            out = os.path.join(DIST, doc['out'] + ext)
            if not os.path.exists(out):
                stale.append(f'{doc["out"]}{ext} does not exist')
            elif os.path.getmtime(out) < max(src, newest_fig):
                age = (max(src, newest_fig) - os.path.getmtime(out)) / 3600
                stale.append(f'{doc["out"]}{ext} is {age:.1f} h behind its source')
    for s in stale:
        print('  STALE  ' + s)
    return 1 if stale else 0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--no-pdf', action='store_true')
    ap.add_argument('--check', action='store_true',
                    help='exit non-zero if dist/ is behind course/')
    a = ap.parse_args()
    if a.check:
        r = check()
        print('  dist/ is current' if not r else '  run: python3 tools/build_docs.py')
        sys.exit(r)

    need('pandoc')
    os.makedirs(DIST, exist_ok=True)
    with tempfile.TemporaryDirectory() as tmp:
        ref = reference_doc(tmp)
        for doc in DOCS:
            build(doc, ref, tmp, not a.no_pdf)
    print('\nBuilt from course/*.md. Re-run this whenever the markdown changes.')


if __name__ == '__main__':
    main()
